version: "3.8"

services:
  pgsql:
    image: postgres:15.7
    container_name: boardava-pgsql
    restart: always
    environment:
      POSTGRES_USER: boardava
      POSTGRES_PASSWORD: boardava
    volumes:
      - pgsql:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - service

networks:
  service:
    name: boardgame-service

volumes:
  pgsql: